openfisca/openfisca-ops

auto-update-ssl-certificates/README.md

add procedure to renew ssl certificates for all domain without stop nginx service

Add "auto update SSL certificates" section

---

auto-update-pip-packages/update-openfisca-virtualenv.sh

Connected to openfisca/openfisca-web-api#106

Redeploy new api on OpenFisca releases

---

france-flask-api/deploy.sh
france-flask-api/openfisca-web-api.service

Connected to openfisca/openfisca-web-api#129

Move API config to Openfisca-Ops

---

france-flask-api/deploy.sh
france-flask-api/openfisca-web-api-new.service

Connected to openfisca/openfisca-web-api#129

Move preview API config to Openfisca-Ops	

---

auto-update-pip-packages/requirements.txt

Use the tracker version defined in OpenFisca-Core

---

auto-update-pip-packages/requirements.txt
fr.openfisca.org/api/deploy.sh
fr.openfisca.org/api/openfisca-web-api-new.service
fr.openfisca.org/api/requirements.txt

Connected to openfisca/openfisca-core#576
Depends on openfisca/openfisca-core#583
Should be merged and applied right before merging openfisca/openfisca-core#583 to avoid any service interruption.

Update extension service and deployment script

---

README.md
fr.openfisca.org/api/v19/deploy.sh
fr.openfisca.org/api/v19/openfisca-web-api-fr19.service
fr.openfisca.org/api/v19/requirements.txt
fr.openfisca.org/fr.openfisca.org.conf

Configure server for `fr.openfisca.org/api/v19`:
* Add systemd service
* Update nginx configuration

Add api configuration to serve openfisca-france v19

---

fr.openfisca.org/api/v20/deploy.sh
fr.openfisca.org/api/v20/openfisca-web-api-fr20.service
fr.openfisca.org/api/v20/requirements.txt
fr.openfisca.org/fr.openfisca.org.conf

Configure server for fr.openfisca.org/api/v20:
Add systemd service
Update nginx configuration

Add api configuration to serve openfisca-france v20

---

fr.openfisca.org/api/v20/openfisca-web-api-fr20.service

Patch of openfisca-france V20 version with hotfix
On the server : 
- creation of a `api-fr20-patch` virtualenv with a openfisca-france version on the hotfix branch
- modification of the .service file so that `api/v20`points to the `api-fr20-patch` virtualenv

Patch V20 version with to handle outdated parameters

---

README.md
fr.openfisca.org/api/v20/openfisca-web-api-fr20.service

Following a patch, the PR makes the public api-fr20 point on the master branch.
This PR also document the procedure to update the api.

Point the API back to the openfisca-France master branch

---

fr.openfisca.org/fr.openfisca.org.conf
fr.openfisca.org/website/deploy.sh
fr.openfisca.org/website/fr.openfisca.org-beta.service

connected to openfisca/openfisca-web-site#65
TODO : Set the config to serve 2011 on `/`
This PR sets the config file, the deploy.sh and systemd service to serve the new openfisca website

Ops for new French website

---

CHANGELOG.md

* Remove [non-breaking spaces](https://en.wikipedia.org/wiki/Non-breaking_space) from [changelog](CHANGELOG.md)
* Improve formatting
* Fix formatting bugs

Improve changelog structure and formatting

---

CHANGELOG.md
fr.openfisca.org/api/v19/openfisca-web-api-fr19.service
fr.openfisca.org/api/v20/openfisca-web-api-fr20.service
fr.openfisca.org/api/v21/openfisca-web-api-fr21.service

This PR reduces the number of workers on the API instances so the server won't overload.

Allow less workers so that the server does not overload

---

CHANGELOG.md
fr.openfisca.org/fr.openfisca.org.conf

fixes openfisca/tracker#8
This PR allow good tracking of the different API versions and of the legislation explorer

Add pathname to have good tracking

---

fr.openfisca.org/api/v21/deploy.sh
fr.openfisca.org/api/v21/openfisca-web-api-fr21.service
fr.openfisca.org/api/v21/requirements.txt

Fixes openfisca/openfisca-core#615
And actually deploy https://github.com/openfisca/openfisca-core/pull/682
https://fr.openfisca.org/api/v21 gives:
```JSON
{"welcome":"Welcome to the OpenFisca-France Web API. To learn how to use it, check our interactive swagger documentation: https://fr.openfisca.org/legislation/swagger."}
```

Use a custom welcome message

---

README.md

Use Python 3.7

---

README.md
auto-update-ssl-certificates/README.md
demo.openfisca.org/demo.openfisca.org.conf
guides/Set-up-SSL.md

Serve demo over https

---

fr.openfisca.org/fr.openfisca.org.conf

Follow-up to #83 which was incomplete 😞

Also serve our content at api.fr.openfisca.org on SSL

---

fr.openfisca.org/api/latest/deploy.sh
fr.openfisca.org/api/latest/requirements.txt

Upgrade France during /latest deploy

---

README.md

Add my GitHub user to the list of people who are authorized to open the Keepass file.

Add my GitHub user

---

guides/Operate-production-services.md

Cf https://github.com/openfisca/openfisca-doc/issues/256#issuecomment-954802299
Thanks @fpagnoux :)

Add details about openfisca-doc
